### ISSUE TITLE
Using a custom style

### ISSUE THREAD

**Issue by astorije** [leonelgalan/linter-markdownlint#4]
In our project, we have our own style file defining which rules must be and must not be enforced. We run the linter as such:

``` sh
mdl --style my-style.mdl.rb .
```

Correct me if I'm wrong, but I don't think there is an equivalent using this linter plugin (or it's missing from the README).

Since there is no convention set for configuration file naming on `mdl` file (and this is how other linter plugins for Atom detect the configuration), I suggest arbitrarily picking a name convention and documenting it in the README.
For example: 

> If `style.mdl.rb` exists at the root of your repository, it will be used as a custom style to run `mdl`. Otherwise, ...

Does this sound reasonable?

**Comment by lloeki** [comment]
Well, in fact, there is, you can use `.mdlrc` at the root of your project (since 0.3.1 or something, before that it was possible but cumbersome) containing:

```ruby
style ".mdl.style.rb"
```

The above is what I typically use, and `mdl` will pick it up automatically.

**Comment by travi** [comment]
My team uses the node version through [markdownlint-cli](https://github.com/igorshubovych/markdownlint-cli) on several projects. That version uses a [`.markdownlintrc`](https://github.com/igorshubovych/markdownlint-cli#configuration) file to specify config options. 

Any chance this package could support that as well?

**Comment by leonelgalan** [comment]
Running `mdl README.md` in my terminal, correctly picks up _.mdlrc_ and it's included _.markdown.style.rb_, but when I run it on atom, i'm seeing many errors that should have been silenced.

What's the best way to troubleshoot this and help find out a solution?

**Comment by leonelgalan** [comment]
@astorije, after #8 (v1.0.2 was published just now) you should be able to create a `.mdlrc` in your project's root with `style 'my-style.mdl.rb'`

@travi this tools is a wrapper for [markdownlint/markdownlint](https://github.com/markdownlint/markdownlint (the gem), I'm not entirely sure about [igorshubovych/markdownlint-cli](https://github.com/igorshubovych/markdownlint-cli), but it appears that the only share the rule names because the underlaying node package was inspired by the ruby version. Have you tried [AtomLinter/linter-markdown](https://github.com/AtomLinter/linter-markdown), it seems more node friendly.
